### PR TITLE
[i18n] Fix sneaky unicode characters in .po files and english .jsons

### PR DESCRIPTION
**Pull request by javnik36**
By-product and continuation of #1352.

This PR fixes unicode characters from [Combining Diacritical Marks Unicode Block](https://www.compart.com/en/unicode/block/U+0300) used in combination with other character that have their own glyph (e.g. found `U+0301` mark preceded by char. `e` will be changed by character `é`). I only changed combination of characters where I was able to confirm that new glyph is used in given locale (and combination is rather not used).

As original EN .jsons were also touched, you may want to rebuild all .po's after this PR is merged.

### CODE REVIEW

**Comment by javnik36** [comment]
List of cases that I did not make any changes:

(1st char, `unicode of 2nd char`, #line in file, word sequence with combination of chars, file in which combination was found)
о	`U+0301`	29	"по́том."     ru: dwl/armitages_fate.po
о	`U+0301`	19	"во́роны"     ru: tcu/union_and_disillusion.po
а	`U+0301`	47	"замка́"      ru: tfa/heart_of_the_elders_part_1.po
о	`U+0301`	57	"Про́кляты"   ru: tfa/heart_of_the_elders_part_2.po
,	`U+0301`	130	"удно,́ слов" ru: tfa/the_city_of_archives.po
о	`U+0301`	100	"мо́чи"       ru: tfa/those_held_captive.po
о	`U+0301`	109	"по́том."     ru: tfa/those_held_captive.po
ы	`U+0301`	1013 "временны́х" rules\ru\rules.json

Some or all of them may be correct, but I lack knowledge of Cyrillic. Tagging @Evgeny727 (hope you don't mind), you may want to check if they are correct.

**Review by Evgeny727 — CHANGES_REQUESTED** [review]
Hi, in result you doesn't changed anything (at least visually), so I think it's be better to doesn't change ru files.
P.s. we adding diacritic marks manually as we nedded, so we doesn't need to change something.

**Comment by javnik36** [comment]
Ok, I left out ru files and submitted my findings in #1355. You may take a look if you are interested :)

**Comment by zzorba** [comment]
Thanks for this, will get it deployed in a week or so.

**Pull request merged**
